module.exports = {

    suites: [
        {
            name: 'Self Service',
            cases: [
                { path: './Self Service/1 - SelfService Prepaid credit with limit.js' },
                { path: './Self Service/2 - SelfService Prepaid credit no limit.js' },
                { path: './Self Service/3 - SelfService Prepaid credit over limit.js' },
                { path: './Self Service/4 - SelfService Prepaid credit 0 with limit.js' },
                { path: './Self Service/5 - SelfService Prepaid credit 0 no limitjs.js' },
                { path: './Self Service/6 - SelfService PrePaid Credit with Hot Club Discount.js' },
                { path: './Self Service/7 - SelfService Prepaid dlkn card with limit.js' },
                { path: './Self Service/8 - SelfService Prepaid dlkn card no limit.js' },
                { path: './Self Service/9 - SelfService Prepaid dlkn card over limit.js' },
                { path: './Self Service/10 - SelfService Prepaid dlkn card with wrong car num.js' },

                { path: './Self Service/12 - SelfService Prepaid dlkn card with wrong code.js' },
                { path: './Self Service/13 - SelfService prepaid IDF card + code with limit.js' },
                { path: './Self Service/14 - SelfService prepaid IDF card + code with no limit.js' },
                { path: './Self Service/15 - SelfService prepaid IDF card  משהבט + code with limit.js' },
                { path: './Self Service/16 - SelfService prepaid IDF card  משהבט + code with no limit.js' },
                { path: './Self Service/17 - SelfService prepaid IDF card  משהבט + no code with limit.js' },
                { path: './Self Service/18 - SelfService prepaid IDF card  משהבט + no code  no limit.js' },
                { path: './Self Service/19 - SelfService prepaid IDF dlkn + code with Digital code צריך להקליט מחדש.js' },
                { path: './Self Service/20 - SelfService prepaid IDF dlkn + no code with Digital code צריך להקליט מחדש.js' },
            ],
        },
        {
            name: 'Full Service',
            cases: [
                { path: './Full Service/1 - FullService prepaid credit with limit.js' },
                { path: './Full Service/2 - FullService prepaid credit no limit.js' },
                { path: './Full Service/3 - FullService prepaid credit with limit 99999.js' },
                { path: './Full Service/4 - FullService prepaid credit 0 with limit.js' },
                { path: './Full Service/5 - FullService prepaid credit 0 no limit.js' },
                { path: './Full Service/6 - FullService Prepaid hot club credit.js' },
                { path: './Full Service/7 - FullService prepaid cash with limit.js' },
                { path: './Full Service/8 - FullService prepaid cash no limit.js' },
                { path: './Full Service/9 - FullService Prepaid cash Taxi Club card with Limit.js' },
                { path: './Full Service/10 - FullService prepaid dlkn card with limit.js' },
                { path: './Full Service/11 - FullService prepaid dlkn card no limit.js' },
                { path: './Full Service/12 - FullService prepaid dlkn card over limit.js' },
                { path: './Full Service/13 - FullService prepaid dlkn card with limit wrong fuel.js' },
                { path: './Full Service/14 - FullService prepaid dlkn card no limit wrong fuel.js' },
                { path: './Full Service/15 - FullService prepaid dlkn card with wrong car number.js' },
                { path: './Full Service/16 - FullService Prepaid Tlushim.js' },
                { path: './Full Service/17 - FullService prepaid IDF card + code with limit.js' },
                { path: './Full Service/18 - FullService prepaid IDF card + code with no limit.js' },
                { path: './Full Service/19 - FullService prepaid IDF card  משהבט + code with limit.js' },
                { path: './Full Service/25 - FullService PrePaid Product with credit.js' },
                { path: './Full Service/26 - FullService PrePaid two Products with same type.js' },
                { path: './Full Service/27 - FullService PrePaid two Products with different type.js' },
                { path: './Full Service/28 - FullService PrePaid two Products with same type and more different one.js' },
                { path: './Full Service/29 - FullService PrePaid Product with dlkn card.js' },
                { path: './Full Service/30 - FullService PrePaid Product with AddOn Discount.js' },
                { path: './Full Service/31 - FullService PrePaid Product with cash.js' },
                { path: './Full Service/32 - FullService PrePaid two Products in cash with different type.js' },
            ],
        },
        {
            name: 'Allocated DualService',
            cases: [
                { path: './Allocated Dual Service/1 - Allocated DualService FullService Prepaid credit with limit.js' },
                { path: './Allocated Dual Service/2 - Allocated DualService FullService Prepaid credit no limit.js' },
                { path: './Allocated Dual Service/3 - Allocated DualService FullService Prepaid credit over limit.js' },
                { path: './Allocated Dual Service/4 - Allocated DualService FullService credit 0 with limit.js' },
                { path: './Allocated Dual Service/5 - Allocated DualService FullService credit 0 no limit.js' },
                { path: './Allocated Dual Service/7 - Allocated DualService FullService prepaid cash with limit.js' },
                { path: './Allocated Dual Service/8 - Allocated DualService FullService prepaid cash no limit.js' },
                { path: './Allocated Dual Service/9 - Allocated DualService FullService prepaid taxi card.js' },
                { path: './Allocated Dual Service/10 - Allocated DualService FullService prepaid dlkn card with limit.js' },
                { path: './Allocated Dual Service/11 - Allocated DualService FullService prepaid dlkn card no limit.js' },
                { path: './Allocated Dual Service/12 - Allocated DualService FullService prepaid dlkn card over limit.js' },
                { path: './Allocated Dual Service/13 - Allocated DualService FullService prepaid dlkn card with limit wrong fuel.js' },
                { path: './Allocated Dual Service/14 - Allocated DualService FullService prepaid dlkn card no limit wrong fuel.js' },
                { path: './Allocated Dual Service/15 - Allocated DualService FullService prepaid dlkn card wrong vehicle number.js' },
                { path: './Allocated Dual Service/17 - Allocated DualService FullService prepaid IDF card + code with limit.js' },
                { path: './Allocated Dual Service/18 - Allocated DualService FullService prepaid IDF card + code with no limit.js' },
                { path: './Allocated Dual Service/25 - Allocated DualService FullService PrePaid Product with credit.js' },
                { path: './Allocated Dual Service/26 - Allocated DualService FullService PrePaid two Products with same type.js' },
                { path: './Allocated Dual Service/27 - Allocated DualService FullService PrePaid two Products with different type.js' },
                { path: './Allocated Dual Service/28 - Allocated DualService FullService PrePaid two Products with same type and more different one.js' },
                { path: './Allocated Dual Service/30 - Allocated DualService FullService PrePaid Product with dlkn card.js' },
                { path: './Allocated Dual Service/31 - Allocated DualService FullService PrePaid Product with AddOn Discount.js' },
                { path: './Allocated Dual Service/32 - Allocated DualService FullService PrePaid Product with cash.js' },
                { path: './Allocated Dual Service/33 - Allocated DualService FullService PrePaid two Products in cash with different type.js' },
                { path: './Allocated Dual Service/35 - Allocated DualService SelfService Prepaid credit with limit.js' },
                { path: './Allocated Dual Service/36 - Allocated DualService SelfService Prepaid credit no limit.js' },
                { path: './Allocated Dual Service/37 - Allocated DualService SelfService Prepaid credit over limit.js' },
                { path: './Allocated Dual Service/38 - Allocated DualService SelfService Prepaid credit 0 with limit.js' },
                { path: './Allocated Dual Service/39 - Allocated DualService SelfService Prepaid credit 0 no limit.js' },
                { path: './Allocated Dual Service/40 - Allocated DualService SelfService PrePaid Credit with Hot Club Discount הועבר לבדיקות הידניות.js' },
                { path: './Allocated Dual Service/41 - Allocated DualService SelfService Prepaid dlkn card with limit.js' },
                { path: './Allocated Dual Service/42 - Allocated DualService SelfService Prepaid dlkn card no limit.js' },
                { path: './Allocated Dual Service/43 - Allocated DualService SelfService Prepaid dlkn card over limit.js' },
                { path: './Allocated Dual Service/45 - Allocated DualService SelfService Prepaid dlkn card with wrong car num.js' },
                { path: './Allocated Dual Service/46 - Allocated DualService SelfService Prepaid dlkn card with wrong code.js' },
                { path: './Allocated Dual Service/47 - Allocated DualService SelfService prepaid IDF card + code with limit.js' },
                { path: './Allocated Dual Service/48 - Allocated DualService SelfService prepaid IDF card + code with no limit.js' },
                { path: './Allocated Dual Service/49 - Allocated DualService SelfService prepaid IDF card  משהבט + code with limit.js' },
                { path: './Allocated Dual Service/50 - Allocated DualService SelfService prepaid IDF card  משהבט + code with no limit.js' },
                { path: './Allocated Dual Service/51 - Allocated DualService SelfService prepaid IDF card  משהבט + no code with limit.js' },
                { path: './Allocated Dual Service/52 - Allocated DualService SelfService prepaid IDF card  משהבט + no code  no limit.js' },
                { path: './Allocated Dual Service/53 - Allocated DualService SelfService prepaid IDF dlkn + code with Digital code.js' },
                { path: './Allocated Dual Service/54 - Allocated DualService SelfService prepaid IDF dlkn + no code with Digital code.js' },
            ],
        },
        {
            name: 'NotAllocatedDualService',
            cases: [
                { path: './NotAllocatedDualService/1 - NotAllocatedDualService FullService Prepaid credit with limit.js' },
                { path: './NotAllocatedDualService/2 - NotAllocatedDualService FullService Prepaid credit no limit.js' },
                { path: './NotAllocatedDualService/3 - NotAllocatedDualService FullService Prepaid credit over limit.js' },
                { path: './NotAllocatedDualService/4 - NotAllocatedDualService FullService credit 0 with limit.js' },
                { path: './NotAllocatedDualService/5 - NotAllocatedDualService FullService credit 0 no limit.js' },
                { path: './NotAllocatedDualService/6 - NotAllocatedDualService FullService prepaid Credit with Hot Club Discount.js' },
                { path: './NotAllocatedDualService/7 - NotAllocatedDualService FullService prepaid cash with limit.js' },
                { path: './NotAllocatedDualService/8 - NotAllocatedDualService FullService prepaid cash no limit.js' },
                { path: './NotAllocatedDualService/9 - NotAllocatedDualService FullService prepaid taxi card.js' },
                { path: './NotAllocatedDualService/10 - NotAllocatedDualService FullService prepaid dlkn card with limit.js' },
                { path: './NotAllocatedDualService/11 - NotAllocatedDualService FullService prepaid dlkn card no limit.js' },
                { path: './NotAllocatedDualService/12 - NotAllocatedDualService FullService prepaid dlkn card over limit.js' },
                { path: './NotAllocatedDualService/13 - NotAllocatedDualService FullService prepaid dlkn card with limit wrong fuel.js' },
                { path: './NotAllocatedDualService/14 - NotAllocatedDualService FullService prepaid dlkn card no limit wrong fuel.js' },
                { path: './NotAllocatedDualService/15 - NotAllocatedDualService FullService prepaid dlkn card wrong vehicle number.js' },
                { path: './NotAllocatedDualService/25 - NotAllocatedDualService FullService PrePaid Product with credit.js' },
                { path: './NotAllocatedDualService/26 - NotAllocatedDualService FullService PrePaid two Products with same type.js' },
                { path: './NotAllocatedDualService/27 - NotAllocatedDualService FullService PrePaid two Products with different type.js' },
                { path: './NotAllocatedDualService/28 - NotAllocatedDualService FullService PrePaid two Products with same type and more different one.js' },
                { path: './NotAllocatedDualService/30 - NotAllocatedDualService FullService PrePaid Product with dlkn card.js' },
                { path: './NotAllocatedDualService/31 - NotAllocatedDualService FullService PrePaid Product with AddOn Discount.js' },
                { path: './NotAllocatedDualService/32 - NotAllocatedDualService FullService PrePaid Product with cash.js' },
                { path: './NotAllocatedDualService/33 - NotAllocatedDualService FullService PrePaid two Products in cash with different type.js' },
                { path: './NotAllocatedDualService/35 - NotAllocatedDualService SelfService Prepaid credit with limit.js' },
                { path: './NotAllocatedDualService/36 - NotAllocatedDualService SelfService Prepaid credit no limit.js' },
                { path: './NotAllocatedDualService/37 - NotAllocatedDualService SelfService Prepaid credit over limit.js' },
                { path: './NotAllocatedDualService/38 - NotAllocatedDualService SelfService Prepaid credit 0 with limit.js' },
                { path: './NotAllocatedDualService/39 - NotAllocatedDualService SelfService Prepaid credit 0 no limit.js' },
                { path: './NotAllocatedDualService/40 - NotAllocatedDualService SelfService PrePaid Credit with Hot Club Discount.js' },
                { path: './NotAllocatedDualService/41 - NotAllocatedDualService SelfService Prepaid dlkn card with limit.js' },
                { path: './NotAllocatedDualService/42 - NotAllocatedDualService SelfService Prepaid dlkn card no limit.js' },
                { path: './NotAllocatedDualService/43 - NotAllocatedDualService SelfService Prepaid dlkn card over limit.js' },
                { path: './NotAllocatedDualService/44 - NotAllocatedDualService SelfService Prepaid dlkn card with wrong fuel type.js' },
                { path: './NotAllocatedDualService/45 - NotAllocatedDualService SelfService Prepaid dlkn card with wrong car num.js' },
                { path: './NotAllocatedDualService/46 - NotAllocatedDualService SelfService Prepaid dlkn card with wrong code.js' },
                { path: './NotAllocatedDualService/47 - NotAllocatedDualService SelfService prepaid IDF card + code with limit.js' },
                { path: './NotAllocatedDualService/48 - NotAllocatedDualService SelfService prepaid IDF card + code with no limit.js' },
                { path: './NotAllocatedDualService/49 - NotAllocatedDualService SelfService prepaid IDF card משהבט + code with limit.js' },
                { path: './NotAllocatedDualService/50 - NotAllocatedDualService SelfService prepaid IDF card  משהבט + code with no limit.js' },
                { path: './NotAllocatedDualService/51 - NotAllocatedDualService SelfService prepaid IDF card  משהבט + no code with limit.js' },
                { path: './NotAllocatedDualService/52 - NotAllocatedDualService SelfService prepaid IDF card משהבט + no code  no limit.js' },
                { path: './NotAllocatedDualService/53 - NotAllocatedDualService SelfService prepaid IDF dlkn + code with Digital code.js' },
                { path: './NotAllocatedDualService/54 - NotAllocatedDualService SelfService prepaid IDF dlkn + no code with Digital code.js' },
            ]
        }
    ],

    modules: ['log', 'utils', 'assert', 'shell']

}