module.exports = {
    authLayout: '//div[@class="auth-layout" or @data-ui-interface="auth_login"]',
    loginForm: 'id=login_form',
    emailInput: '//input[@type="email" or name="email"]',
    passwordInput: '//input[@type="password" or name="password"]',
    loginButton: '//button[@data-ui-action="login" and not(@disabled)]',
    invalidInput: '//input[@class="fill input__field error"]',
    inputErrorMessage: '//span[@class="input__hint error"]',
    passwordValidationErrors: '//ul[contains(@class, "auth__password-validations")]//li[@class="error"]',
    passwordValidationActives: '//ul[contains(@class, "auth__password-validations")]//li[@class="active"]',
    forgotPasswordButton: '//a[@data-ui-action="forgot_password"]',
    forgotPasswordForm: 'id=forgot_password_form',
    forgotPasswordFormHeader: '//*[contains(text(), "Forgot your password?")]',
    forgotPasswordSendButton: '//form[@id="forgot_password_form"]//button[@type="submit"]',
    backButton: '//a[contains(text(), "Back")]',
    resetPasswordConfirmationText: '//div[contains(@class, "auth__confirmation-descr") and contains(text(), "password reset")]',
    resetPasswordForm: 'id=reset_password_form',
    newPasswordInput: '//span[contains(text(), "New Password")]//..//input',
    updatePasswordButton: '//span[contains(text(), "Update Password")]',
    repeatPasswordInput: '//span[contains(text(), "Repeat Password")]//..//input',
    backToLoginButton: '//a[contains(text(), "Back to Login")]',
    contactUsButton: '//a[contains(text(), "Contact us")]',
    createAccountButton: '//a[@data-ui-action="register"]',
    accountMenu: '//div[@class="dashboard__header-account"]',
    toastMessage: '//div[contains(@class, "toastify")]',
    logoutButton: '//a[contains(text(), "Logout")]',
    accountButton: '//a[contains(text(), "Account")]',
    saveButton: '//button[contains(text(), "Save")]',
    accountSettingsFirstNameInput: '//span[contains(text(), "First name")]//..//input',
    accountSettingsLastNameInput: '//span[contains(text(), "Last name")]//..//input',
    accountSettingsCurrentPasswordInput: '//span[contains(text(), "Current password")]//..//input',
    accountSettingsNewPasswordInput: '//span[contains(text(), "New password")]//..//input',
    accountSettingsConfirmNewPasswordInput: '//span[contains(text(), "Confirm new password")]//..//input',
    signupForm: 'id=signup_form',
    signupFormHeader: '//*[contains(text(), "Sign up")]',
    signupNextButton: '//form[@id="signup_form"]//button[@type="submit" and not(@disabled)]',
    signupNextButtonDisabled: '//form[@id="signup_form"]//button[@type="submit" and @disabled]',
    signupInputField: '//form[@id="signup_form"]//input[contains(@name, "") and not(@class="sys-hide")]',
    signupInput: (fieldName) => { return `//form[@id="signup_form"]//input[contains(@name, "${fieldName}")]` },
    // first_name last_name email password password_confirmation promo
}