module.exports = {
    welcomeHeader: '//div[@class="heading-line"]',
    backButton: '//a[@class="dashboard__header-back-link"]',
    dashboardContent: '//main[contains(@class, "dashboard__content")]',
    suggestedProductsSection: '(//div[contains(@class, "suggested-products")])[1]',
    firstProductInSuggestedProductsSection: '(//div[contains(@class, "suggested-products")]//a[@class="product"])[1]',
    seeAllSuggestedProductsButton: '//div[@class="suggested-products__actions"]',
    suggestedProductsSwiper: '//div[@class="swiper-wrapper"]',
    suggestedProductsSwipePrevButton: '//div[@class="swiper-button-prev"]',
    suggestedProductsSwipeNextButton: '//div[@class="swiper-button-next"]',
    costumPrintedProductsGrid: '//div[@class="products-grid filter-products"]',
    costumPrintedProducts: '//div[@class="products-grid filter-products"]//a[@class="product"]',
    productItem: '//div[@class="product_item"]',
    productItemName: '//div[@class="product_item"]//*[@class="name"]',
    productItemDescription: '//div[@class="product_item"]//*[@class="description"]',
    productItemPrice: '//div[@class="product_item"]//*[@class="price"]',
    productItemShipping: '//div[@class="product_item"]//*[@class="shipping"]',
    dashboardNavLink: '//nav[@class="dashboard__nav"]//span[text()="Dashboard"]',
}