module.exports = {
    authLayout: '//div[@class="auth-layout" and @data-ui-interface="auth_login"]',
    loginForm: 'id=login_form',
    emailInput: 'name=email',
    passwordInput: 'name=password',
    loginButton: '//button[@data-ui-action="login" and not(@disabled)]',
    inputErrorMessage: '//span[@class="input__hint error"]',
    expectedErrorMessageText: 'These credentials do not match our records.',
    forgotPasswordButton: '//a[@data-ui-action="forgot_password"]',
    forgotPasswordForm: 'id=forgot_password_form',
    forgotPasswordFormHeader: '//*[contains(text(), "Forgot your password?")]',
    backButton: '//a[contains(text(), "Back")]',
    createAccountButton: '//a[@data-ui-action="register"]',
    signupForm: 'id=signup_form',
    signupFormHeader: '//*[contains(text(), "Sign up")]',
}